### ISSUE TITLE
url returns 404

### ISSUE THREAD

**Issue by johannesE** [michaelklishin/phantomjs-chef-cookbook#2]
The following worked for me:
```
arch = kernel['machine'] =~ /x86_64/ ? "x86_64" : "i686"
version = '2.1.1'
default[:phantomjs] = {
    :version => version,
    :arch    => arch,
    :tarball => {
        :url  => "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-#{version}-linux-#{arch}.tar.bz2"
    }
}
```

**Comment by michaelklishin** [comment]
@johannesE this cookbook hasn't been updated in a few years. I have no idea how phantom.js is distributed these days. Feel free to submit a PR if you understand what has to be corrected.

**Comment by johannesE** [comment]
Thanks for your quick reply. If you check the links on the official site (http://phantomjs.org/download.html), you see that they point to that bitbucket/ariya url. See also that gist: https://gist.github.com/julionc/7476620/e8f36f2a2d616720983e8556b49ec21780c96f0c

**Comment by johannesE** [comment]
@michaelklishin Hi Michael
Do you have any comments for my PR?
Best regards,
Joe
